module.exports = {
    "NAME": "BOT_NAME_HERE",
    "TOKEN": "DISCORD_BOT_TOKEN_HERE",
    "WOLFRAM_APP_ID": "WOLFRAM_APP_ID_HERE",
    "KSOFT_SI_V1_API_KEY": "KSOFT_SI_V1_API_KEY_HERE",
    "UNSPLASH_ACCESS_KEY": "UNSPLASH_API_ACCESS_KEY_HERE",
    "HASTEBIN_URL": "HASTEBIN_URL_HERE",
    "SHORT_IO": {
        "SECRET_KEY": "SHORT_IO_SECRET_KEY_HERE",
        "DOMAIN": "SHORT_IO_DOMAIN_HERE"
    },
    "CLIENT_ID": "DISCORD_BOT_CLIENT_ID_HERE",
    "PREFIX": "BOT_PREFIX_HERE",
    "OWNERS": ["OWNER_ID_HERE"]
};